### ISSUE TITLE
ule link_input fails sometimes

### ISSUE THREAD

**Issue by cmkobel** [cmkobel/MS-pipeline1#1]
```ln -s /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_C9_Slot1-33_1_1971.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_C11_Slot1-35_1_1973.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_C12_Slot1-36_1_1974.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D1_Slot1-37_1_1975.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D2_Slot1-38_1_1976.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D3_Slot1-39_1_1977.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D4_Slot1-40_1_1978.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D5_Slot1-41_1_1979.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D6_Slot1-42_1_1980.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D7_Slot1-43_1_1981.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D8_Slot1-44_1_1982.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D9_Slot1-45_1_1983.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D10_Slot1-46_1_1984.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D11_Slot1-47_1_1985.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_D12_Slot1-48_1_1986.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E1_Slot1-49_1_1987.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E2_Slot1-50_1_1988.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E3_Slot1-51_1_1989.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E4_Slot1-52_1_1990.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E5_Slot1-53_1_1991.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E6_Slot1-54_1_1992.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E7_Slot1-55_1_1993.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E8_Slot1-56_1_1994.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E9_Slot1-57_1_1995.d /faststorage/project/gBGC/supacow/raw_data/uplc-msms-timstof/220506_metaP_rumen_digesta_T6/20220525_CMK/20220506_E10_Slot1-58_1_1996.d output/220506_DnnT6S_carl/msfragger

        
Touching output file output/220506_DnnT6S_carl/msfragger/link_input.done.
Traceback (most recent call last):
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/__init__.py", line 726, in snakemake
    success = workflow.execute(
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/workflow.py", line 1133, in execute
    raise e
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/workflow.py", line 1129, in execute
    success = self.scheduler.schedule()
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/scheduler.py", line 423, in schedule
    self._finish_jobs()
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/scheduler.py", line 526, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 633, in handle_job_success
    super().handle_job_success(job)
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 232, in handle_job_success
    job.postprocess(
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/jobs.py", line 1076, in postprocess
    self.dag.check_and_touch_output(
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/dag.py", line 594, in check_and_touch_output
    f.touch()
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/io.py", line 707, in touch
    raise e
  File "/home/cmkobel/faststorage/miniconda3/envs/smk785/lib/python3.10/site-packages/snakemake/io.py", line 693, in touch
    with open(file, "w"):
PermissionError: [Errno 13] Permission denied: 'output/220506_DnnT6S_carl/msfragger/20220506_C9_Slot1-33_1_1971.d/.snakemake_timestamp'```

**Comment by cmkobel** [comment]
I have a strange feeling that the job graph is messing up by running individual jobs for each sample?

**Comment by cmkobel** [comment]
Probably not the problem since rule link_input is going to run once only, for twenty-something samples and an empty output directory.

![Screen Shot 2022-07-18 at 13 28 44](https://user-images.githubusercontent.com/5913696/179501894-3cb4f42f-e843-43c1-8cec-7a3f36dd1adc.png)

**Comment by cmkobel** [comment]
Turned out it was not a bug.
